.TH "TERMICODER DEBUG" "1" "14-Oct-2018" "0.3.0" "termicoder debug Manual"
.SH NAME
termicoder\-debug \- Launches custom debug interface.
.SH SYNOPSIS
.B termicoder debug
[OPTIONS]
.SH DESCRIPTION
Launches custom debug interface.
Here you can use testcase generator,
launch debugger for the particular language
and visualize the output.
.PP
NOTE:
This functionality is not implemented in this version.
This option is only included for compatibility purposes.
If you want to contribute to its development visit:
https://termicoder.github.io/