.TH "TERMICODER VIEW" "1" "22-Sep-2018" "" "termicoder view Manual"
.SH NAME
termicoder\-view \- view contests, problems ad problem statement
.SH SYNOPSIS
.B termicoder view
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
view contests, problems ad problem statement
.SH COMMANDS
.PP
\fBproblem\fP
  list problems of a contest/category
  See \fBtermicoder view-problem(1)\fP for full documentation on the \fBproblem\fP command.
.PP
\fBcontest\fP
  display contest list of a judge
  See \fBtermicoder view-contest(1)\fP for full documentation on the \fBcontest\fP command.
.PP
\fBthis\fP
  view contents of current folder
  See \fBtermicoder view-this(1)\fP for full documentation on the \fBthis\fP command.