.TH "TERMICODER VIEW CONTEST" "1" "14-Oct-2018" "0.3.0" "termicoder view contest Manual"
.SH NAME
termicoder\-view\-contest \- Display a particular contest
.SH SYNOPSIS
.B termicoder view contest
[OPTIONS] [CONTEST_CODE]
.SH DESCRIPTION
View a contest from the judge (online).
Launches the contest in browser.
.SH OPTIONS
.TP
\fB\-j,\fP \-\-judge [codechef]
.PP
.TP
\fB\-\-browser\fP TEXT
Browser to launch