.TH "TERMICODER VIEW THIS" "1" "22-Sep-2018" "" "termicoder view this Manual"
.SH NAME
termicoder\-view\-this \- view contents of current folder
.SH SYNOPSIS
.B termicoder view this
[OPTIONS] [DIR]
.SH DESCRIPTION
display the termicoder contents in current/passed folder
.PP

if it is a contest folder it displays the list of problems.
if its a problem folder, displays the problem in a browser.
.SH OPTIONS
.TP
\fB\-ed,\fP \-\-edit_defaults
edit default web browser