.TH "TERMICODER VIEW FOLDER" "1" "14-Oct-2018" "0.3.0" "termicoder view folder Manual"
.SH NAME
termicoder\-view\-folder \- View contents of folder.
.SH SYNOPSIS
.B termicoder view folder
[OPTIONS] [DIR_NAME]
.SH DESCRIPTION
display the termicoder contents in current/passed folder
.PP

if it is a contest folder it displays the list of problems.
if its a problem folder, displays the problem in a browser.
.SH OPTIONS
.TP
\fB\-\-browser\fP TEXT
Browser to launch