.TH "TERMICODER VIEW" "1" "14-Oct-2018" "0.3.0" "termicoder view Manual"
.SH NAME
termicoder\-view \- View contests and problems.
.SH SYNOPSIS
.B termicoder view
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
View contests and problems.
.SH COMMANDS
.PP
\fBfolder\fP
  View contents of folder.
  See \fBtermicoder view-folder(1)\fP for full documentation on the \fBfolder\fP command.
.PP
\fBrunning\fP
  View all running contests.
  See \fBtermicoder view-running(1)\fP for full documentation on the \fBrunning\fP command.
.PP
\fBcontest\fP
  Display a particular contest
  See \fBtermicoder view-contest(1)\fP for full documentation on the \fBcontest\fP command.
.PP
\fBproblem\fP
  View a particular problem
  See \fBtermicoder view-problem(1)\fP for full documentation on the \fBproblem\fP command.