.TH "TERMICODER CONFIG AUTOCOMPLETE INSTALL" "1" "14-Oct-2018" "0.3.0" "termicoder config autocomplete install Manual"
.SH NAME
termicoder\-config\-autocomplete\-install \- Install the click-completion-command...
.SH SYNOPSIS
.B termicoder config autocomplete install
[OPTIONS] [SHELL] [PATH]
.SH DESCRIPTION
Install the click-completion-command completion
.SH OPTIONS
.TP
\fB\-\-append\fP / \-\-overwrite
Append the completion code to the file
.TP
\fB\-i,\fP \-\-case\-insensitive / \-\-no\-case\-insensitive
Case insensitive completion