.TH "TERMICODER CONFIG" "1" "22-Sep-2018" "" "termicoder config Manual"
.SH NAME
termicoder\-config \- configure termicoder settings, autocomplete...
.SH SYNOPSIS
.B termicoder config
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
configure termicoder settings, autocomplete etc.
.SH OPTIONS
.TP
\fB\-j,\fP \-\-judge []
.PP
.TP
\fB\-c,\fP \-\-contest TEXT
contest code
.TP
\fB\-p,\fP \-\-problem TEXT
problem code
.TP
\fB\-\-login\fP
.PP
.TP
\fB\-\-logout\fP
.PP
.SH COMMANDS
.PP
\fBautocomplete\fP
  Shell completion for termicoder.
  See \fBtermicoder config-autocomplete(1)\fP for full documentation on the \fBautocomplete\fP command.