.TH "TERMICODER CONFIG AUTOCOMPLETE SHOW" "1" "14-Oct-2018" "0.3.0" "termicoder config autocomplete show Manual"
.SH NAME
termicoder\-config\-autocomplete\-show \- Show the click-completion-command completion...
.SH SYNOPSIS
.B termicoder config autocomplete show
[OPTIONS] [SHELL]
.SH DESCRIPTION
Show the click-completion-command completion code
.SH OPTIONS
.TP
\fB\-i,\fP \-\-case\-insensitive / \-\-no\-case\-insensitive
Case insensitive completion