.TH "TERMICODER CODE" "1" "22-Sep-2018" "" "termicoder code Manual"
.SH NAME
termicoder\-code \- creates & open code file with template code.
.SH SYNOPSIS
.B termicoder code
[OPTIONS]
.SH DESCRIPTION
creates & open code file with template code.
.PP
you can edit template code and default editors
using flags -et and -ed respectively
.SH OPTIONS
.TP
\fB\-f,\fP \-\-file PATH
the filename to code into with preloaded template
.TP
\fB\-et,\fP \-\-edit_templates
open templates folder
.TP
\fB\-ed,\fP \-\-edit_defaults
edit defaults for editors