.TH "TERMICODER DEBUG" "1" "22-Sep-2018" "" "termicoder debug Manual"
.SH NAME
termicoder\-debug \- launches custom debug interface (in future)...
.SH SYNOPSIS
.B termicoder debug
[OPTIONS]
.SH DESCRIPTION
launches custom debug interface (in future)
where you can use testcase generator,
launch debugger for the particular language
and visualize the output