.TH "TERMICODER VIEW PROBLEM" "1" "22-Sep-2018" "" "termicoder view problem Manual"
.SH NAME
termicoder\-view\-problem \- list problems of a contest/category
.SH SYNOPSIS
.B termicoder view problem
[OPTIONS]
.SH DESCRIPTION
lists problems of a contest/category on the judge
.SH OPTIONS
.TP
\fB\-j,\fP \-\-judge []
.PP
.TP
\fB\-c,\fP \-\-contest TEXT
contest code