.TH "TERMICODER LIST CONTEST" "1" "14-Oct-2018" "0.3.0" "termicoder list contest Manual"
.SH NAME
termicoder\-list\-contest \- List a particular contest.
.SH SYNOPSIS
.B termicoder list contest
[OPTIONS]
.SH DESCRIPTION
List problems from a particular contest with their status.
.PP
depending on judge it may give a list of categories also
such as PRACTICE etc.
.SH OPTIONS
.TP
\fB\-j,\fP \-\-judge [codechef]
.PP