.TH "TERMICODER CLIP" "1" "14-Oct-2018" "0.3.0" "termicoder clip Manual"
.SH NAME
termicoder\-clip \- Copies code from file to clipboard.
.SH SYNOPSIS
.B termicoder clip
[OPTIONS] [CODE_FILE]
.SH DESCRIPTION
Copies code from CODE_FILE to the clipboard.
.PP
If CODE_FILE is not passed, a default file is suggested based
on current directory.
.PP
The suggested file is the most recently edited code file
recognized by termicoder.