.TH "TERMICODER SUBMIT" "1" "14-Oct-2018" "0.3.0" "termicoder submit Manual"
.SH NAME
termicoder\-submit \- Submit a solution.
.SH SYNOPSIS
.B termicoder submit
[OPTIONS] [CODE_FILE]
.SH DESCRIPTION
Submit a solution.
.PP
You should be in a problem directory to submit
.PP

Script will prompt you to login into the judge(if not already).