.TH "TERMICODER VIEW PROBLEM" "1" "14-Oct-2018" "0.3.0" "termicoder view problem Manual"
.SH NAME
termicoder\-view\-problem \- View a particular problem
.SH SYNOPSIS
.B termicoder view problem
[OPTIONS] PROBLEM_CODE
.SH DESCRIPTION
View a particular problem from the judge.
.SH OPTIONS
.TP
\fB\-j,\fP \-\-judge [codechef]
.PP
.TP
\fB\-c,\fP \-\-contest TEXT
contest code
.TP
\fB\-\-browser\fP TEXT
Browser to launch