.TH "TERMICODER REPL" "1" "22-Sep-2018" "" "termicoder repl Manual"
.SH NAME
termicoder\-repl \- Start an interactive shell.
.SH SYNOPSIS
.B termicoder repl
[OPTIONS]
.SH DESCRIPTION
Start an interactive shell. All commands and subcommands are available
in it.
.PP
If stdin is not a TTY, no prompt will be printed, but only commands read
from stdin.