.TH "TERMICODER SUBMIT" "1" "22-Sep-2018" "" "termicoder submit Manual"
.SH NAME
termicoder\-submit \- submit a solution.
.SH SYNOPSIS
.B termicoder submit
[OPTIONS]
.SH DESCRIPTION
submit a solution.
.PP
you should be in a problem directory to submit
.PP

script will prompt you to login into the judge(if not already).
this submits the problem using data in [.problem] file in current directory
.SH OPTIONS
.TP
\fB\-f,\fP \-\-file FILENAME
the code file