.TH "TERMICODER LIST" "1" "14-Oct-2018" "0.3.0" "termicoder list Manual"
.SH NAME
termicoder\-list \- List the contents of current folder.
.SH SYNOPSIS
.B termicoder list
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
List the contents of current folder.
.SH COMMANDS
.PP
\fBfolder\fP
  View contents of folder.
  See \fBtermicoder list-folder(1)\fP for full documentation on the \fBfolder\fP command.
.PP
\fBrunning\fP
  View all running contests.
  See \fBtermicoder list-running(1)\fP for full documentation on the \fBrunning\fP command.
.PP
\fBcontest\fP
  List a particular contest.
  See \fBtermicoder list-contest(1)\fP for full documentation on the \fBcontest\fP command.