.TH "TERMICODER" "1" "22-Sep-2018" "" "termicoder Manual"
.SH NAME
termicoder \- hello
.SH SYNOPSIS
.B termicoder
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
view, code & submit problems directly from terminal.
.SH COMMANDS
.PP
\fBsetup\fP
  sets up problem, contests and login.
  See \fBtermicoder-setup(1)\fP for full documentation on the \fBsetup\fP command.
.PP
\fBtest\fP
  test code against the sample testcases.
  See \fBtermicoder-test(1)\fP for full documentation on the \fBtest\fP command.
.PP
\fBdebug\fP
  launches custom debug interface (in future)...
  See \fBtermicoder-debug(1)\fP for full documentation on the \fBdebug\fP command.
.PP
\fBsubmit\fP
  submit a solution.
  See \fBtermicoder-submit(1)\fP for full documentation on the \fBsubmit\fP command.
.PP
\fBcode\fP
  creates & open code file with template code.
  See \fBtermicoder-code(1)\fP for full documentation on the \fBcode\fP command.
.PP
\fBview\fP
  view contests, problems ad problem statement
  See \fBtermicoder-view(1)\fP for full documentation on the \fBview\fP command.
.PP
\fBrepl\fP
  Start an interactive shell.
  See \fBtermicoder-repl(1)\fP for full documentation on the \fBrepl\fP command.
.PP
\fBconfig\fP
  configure termicoder settings, autocomplete...
  See \fBtermicoder-config(1)\fP for full documentation on the \fBconfig\fP command.