.TH "TERMICODER CONFIG AUTOCOMPLETE" "1" "22-Sep-2018" "" "termicoder config autocomplete Manual"
.SH NAME
termicoder\-config\-autocomplete \- Shell completion for termicoder.
.SH SYNOPSIS
.B termicoder config autocomplete
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Shell completion for termicoder.
Available shell types:

  bash         Bourne again shell
  fish         Friendly interactive shell
  powershell   Windows PowerShell
  zsh          Z shell
Default type: auto
.SH COMMANDS
.PP
\fBinstall\fP
  Install the click-completion-command...
  See \fBtermicoder config autocomplete-install(1)\fP for full documentation on the \fBinstall\fP command.
.PP
\fBshow\fP
  Show the click-completion-command completion...
  See \fBtermicoder config autocomplete-show(1)\fP for full documentation on the \fBshow\fP command.