.TH "TERMICODER VIEW CONTEST" "1" "22-Sep-2018" "" "termicoder view contest Manual"
.SH NAME
termicoder\-view\-contest \- display contest list of a judge
.SH SYNOPSIS
.B termicoder view contest
[OPTIONS]
.SH DESCRIPTION
lists current and upcoming contests on a judge.
.PP
depending on judge it may give a list of categories also
such as PRACTICE etc.
.SH OPTIONS
.TP
\fB\-j,\fP \-\-judge []
.PP