.TH "TERMICODER CONFIG" "1" "14-Oct-2018" "0.3.0" "termicoder config Manual"
.SH NAME
termicoder\-config \- Configure settings, autocomplete etc.
.SH SYNOPSIS
.B termicoder config
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Configure settings, autocomplete etc.
.SH COMMANDS
.PP
\fBman\fP
  Setup man pages.
  See \fBtermicoder config-man(1)\fP for full documentation on the \fBman\fP command.
.PP
\fBremove\fP
  Remove the configuration directory.
  See \fBtermicoder config-remove(1)\fP for full documentation on the \fBremove\fP command.
.PP
\fBedit\fP
  Edit the configuration.
  See \fBtermicoder config-edit(1)\fP for full documentation on the \fBedit\fP command.
.PP
\fBinit\fP
  Initialize the config directory.
  See \fBtermicoder config-init(1)\fP for full documentation on the \fBinit\fP command.
.PP
\fBautocomplete\fP
  Shell completion for termicoder.
  See \fBtermicoder config-autocomplete(1)\fP for full documentation on the \fBautocomplete\fP command.