.TH "TERMICODER VIEW RUNNING" "1" "14-Oct-2018" "0.3.0" "termicoder view running Manual"
.SH NAME
termicoder\-view\-running \- View all running contests.
.SH SYNOPSIS
.B termicoder view running
[OPTIONS]
.SH DESCRIPTION
View all running contests.
.SH OPTIONS
.TP
\fB\-j,\fP \-\-judge [codechef]
.PP
.TP
\fB\-\-browser\fP TEXT
Browser to launch